---
functional:
  - Пользователь должен иметь возможность зарегистрироваться в игре.
  - Пользователь должен иметь возможность авторизоваться.
  - Пользователь должен иметь возможность создавать игры или турниры (с ботом, другом или другим пользователем).
  - Пользователь должен иметь возможность вступать в игру с другими участниками (по приглашению или по собственному выбору).
  - Пользователь должен иметь возможность выбора определенной игры или (по выбору) подобранной случайным образом.
  - Пользователь должен иметь возможность выбирать для решения задач языки программирования.
  - Сайт должен отображать рейтинг игроков и статистику игр.
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы.
  - Сайт должен иметь мобильную версию.
  - Сайт нужно протестировать на совместимость с последними версиями браузеров.
  - Сайт должен обрабатывать большое количество трафика (например, 1000 одновременных пользователей).
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - Сайт должен предоставлять пользователю возможность игры в упрощенном режиме без авторизации. 
  - Площадка должна иметь чат и возможность отправки личных сообщений от пользователя - пользователю.
  - На площадке должна быть реализована возможность игры для пользователей с минимальной подготовкой.
  - Пользователям должна быть предоставлена возможность просмотра проведенных ими игр в записи.
  - Пользователи должны иметь возможность следить за игрой других пользователей.
